add_newline = false
[line_break]
disabled = true
[package]
disabled = true
[cmd_duration]
disabled = true
[hostname]
ssh_only = true
style = "bold green"
format = "[$hostname]($style) "
[username]
show_always = false
format = "[$user]($style) "
[python]
format='[(\($virtualenv\) )]($style)'
[nodejs]
disabled = true
[git_branch]
format = "[$symbol$branch]($style) "
[lua]
disabled = true
